{{- if .Values.serviceAccount.create }}
{{- $annotations := .Values.serviceAccount.annotations | default dict }}
{{- with .Values.serviceAccount.gcpServiceAccount }}
{{- $annotations = merge (dict "iam.gke.io/gcp-service-account" .) $annotations }}
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gcp-capacity-exporter.serviceAccountName" . }}
  labels:
    {{- include "gcp-capacity-exporter.labels" . | nindent 4 }}
  {{- with $annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}
